stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: klakegg/hugo:0.76.5-alpine
    entrypoint: [""]
  script:
    - hugo
    - cp -R netlify/ public/admin/
  only:
    - main

deploy:
  stage: deploy
  script:
    - curl http://hook.srv.imabot.nl:9000/hooks/deploy-eline-harbers?token=$CI_JOB_TOKEN&secret=$WEBHOOK_TOKEN
  only:
    - main
