stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: klakegg/hugo:0.76.5-alpine
    entrypoint: [""]
  script:
    - hugo
    - cp -R netlify/ public/admin/
  artifacts:
    expire_in: 2hrs
    paths:
      - plublic/
  only:
    - main

deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y curl
    - 'OUTPUT="$(curl https://hook.srv.imabot.nl/hooks/deploy-eline-harbers?token=$CI_JOB_TOKEN&secret=$WEBHOOK_TOKEN)"'
    - echo $OUTPUT
  only:
    - main
