backend:
  name: github
  repo: S-D-V-A-S-M-V-V-I-C-T-S-S-BAGGER/elineharbers
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "sections"
    label: "Sections"
    files:
      - name: "news"
        label: "In het nieuws"
        file: "data/news.yml"
        fields:
          - {name: "body", label: "Body", widget: "markdown"}
          - {name: "picture", label: "Picture", widget: "image"}
      - name: "dirigent"
        label: "Eline als Dirigent"
        file: "data/dirigent.yml"
        fields:
          - {name: "picture", label: "Picture", widget: "image"}
          - {name: "body", label: "Body", widget: "markdown"}
          - {name: "quote", label: "Quote", widget: "markdown"}
      - name: "zangeres"
        label: "Eline als Zangeres"
        file: "data/zangeres.yml"
        fields:
          - {name: "picture", label: "Picture", widget: "image"}
          - {name: "body", label: "Body", widget: "markdown"}
      - name: "pictures"
        label: "Pictures"
        file: "data/pictures.yml"
        fields:
          - name: "pictures"
            label: "Pictures"
            widget: list
            fields:
              - {name: "picture", label: "Picture", widget: "image"}
      - name: "video"
        label: "Video"
        file: "data/video.yml"
        fields:
          - {name: "video", label: "Video", widget: "string"}
      - name: "media"
        label: "In de media"
        file: "data/media.yml"
        fields:
          - label: "quotes"
            name: "Quotes"
            widget: list
            fields:
              - {name: "quote", label: "Quote", widget: "markdown"}
      - name: "contact"
        label: "Contact"
        file: "data/contact.yml"
        fields:
          - {name: "picture", label: "Picture", widget: "image"}
          - {name: "body", label: "Body", widget: "markdown"}
